defaults:
  - _self_

hydra:
  run:
    dir: plan_outputs/pusht/${now:%Y%m%d%H%M%S}

# model to load for planning
ckpt_path: ./outputs/pusht/
model_epoch: latest

seed: 99
n_evals: 50
goal_source: 'dset'
goal_H: 5 
n_plot_samples: 10

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 0.5
  mode: all

#closed-loop
planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: null
  n_taken_actions: 1
  sub_planner:
    action_noise: 0.003
    eval_every: 80
    horizon: 5
    lr: 0.2
    opt_steps: 100
    optimizer_type: adam
    rollout_type: custom
    sample_type: randn  # 'zero', 'randn', 'initnet'
    target: planning.gd.GDPlanner
  name: mpc_gd

# open-loop
# planner:
#   _target_: planning.gd.GDPlanner
#   horizon: 5
#   action_noise: 0.003
#   sample_type: 'randn' # 'zero', 'randn', 'initnet'
#   lr: 3e-1
#   opt_steps: 300
#   eval_every: 10
#   optimizer_type: "adam"
#   rollout_type: "custom"
#   name: gd
