planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: null # unlimited if null
  n_taken_actions: 1
  sub_planner:
    target: planning.gdcem.GradCEMPlanner
    horizon: 5
    topk: 30
    num_samples: 300
    var_scale: 1
    opt_steps: 30
    grad_steps: 1
    optimizer_type: "adam"
    rollout_type: "custom"
    action_noise: 0.003
    lr: 3e-1
    eval_every: 1
  name: mpc_gdcem