planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: 100
  n_taken_actions: 1
  sub_planner:
    target: planning.mppi.MPPIPlanner
    horizon: 5
    num_samples: 5
    var_scale: 1
    eval_every: 3
    name: mppi
    rollout_type: "custom"
  name: mpc_mppi